### ISSUE TITLE
Reconnection handling

### ISSUE THREAD

**Issue by lholznagel** [jgallagher/amiquip#16]
Hey,
I just stumbled across this library for a project I am working on.
During my testing, I found out that there is no reconnection handling (then I saw it in the documentation). 

I thought about implementing it, but I wanted to ask if there was a reason that you didn´t implement it.

Have a nice day :)

**Comment by jgallagher** [comment]
The short answer is that I think robust and general reconnection handling is very difficult, and I'm inclined to do that in a separate crate that sits on top of `amiquip`. I have one such reconnection layer that makes some project-specific simplifying assumptions, but haven't had the time to make an open source version.

A few of the questions a reconnection layer has to deal with are:

* What is the retry logic? (Mine has an exponential backoff up to some limit between reconnection attempts, but keeps retrying forever.)
* What do you do with messages while you're not connected? (Since the retry logic in mine is "keep trying forever", the reconnection layer allows the application to continue to enqueue messages and it will send them once the connection is reestablished.)
* How to you rebuild the channels, queues, etc.? (This is probably the most project-specific part of mine - it forces a fixed topology to be declared up front, then rebuilds that topology after every reconnection.)

So I'm not opposed to reconnection handling, but currently believe it's better suited as another layer up. Would the implementation you were considering make sense as a separate crate?

**Comment by rtxm** [comment]
Hello,
We handle this in our application code, much in the same way @jgallagher explained. Moreover, we try several broker urls in turn, round-robin style (we use rabbitmq HA clusters).

By the way `amiquip` is really good, thanks @jgallagher!

**Comment by lholznagel** [comment]
Hey, thanks for your answer.
I agree that reconnection handling is hard and that it involves some thinking on how to do it right.

Implementing reconnection handling in a separate crate could be an option.

Have a nice day :)

**Comment by jgallagher** [comment]
Sure thing! If you decide to tackle it and need changes to amiquip itself to make it possible, please let me know.
