### ISSUE TITLE
Prefetch count doesn't work

### ISSUE THREAD

**Issue by zloypacifist** [jgallagher/amiquip#30]
```
let ch = rabbit.open_channel(None).unwrap();
ch.qos(0, 20, true).unwrap();
```
 This code doesn't work.

```
let queue = ch.queue_declare(
            "some_queue",
            QueueDeclareOptions {
                exclusive: false,
                auto_delete: true,
                ..QueueDeclareOptions::default()
            },
 ).unwrap();
```
But in rabbitMq it's still have prefetch count 0

![image](https://user-images.githubusercontent.com/2009979/99768535-bfb51780-2b26-11eb-9989-0cd589608229.png)

**Comment by jgallagher** [comment]
I think you might be looking in the  wrong place because you passed `true` for global. Can you try two things:

* With the code you have now, can you look at the channel settings (not the queue consumer settings)? If I use your code I see

![Screenshot 2020-11-20 172135](https://user-images.githubusercontent.com/1435635/99855448-e5f1ac00-2b54-11eb-87de-ebc49f0b3625.png)

* Try changing global to `false` and check the consumer screen you're looking at, and see if that does it.

**Comment by jgallagher** [comment]
I'm going to close this; please reopen if I was wrong and there's a problem here.
