### ISSUE TITLE
How to retrieve the current queue size

### ISSUE THREAD

**Issue by tappoz** [jgallagher/amiquip#32]
Is there a way to know at runtime the number of messages in a queue?
I am actually interested in the fact that the queue might be empty or not, so comparing the number of current messages to 0.

I've checked here: https://docs.rs/amiquip/0.4.0/amiquip/struct.Queue.html but it looks like this information is not available from the Rust library?

Thanks

**Comment by jgallagher** [comment]
I believe there are two ways to do this, both of which are available:

1. https://docs.rs/amiquip/0.4.0/amiquip/struct.Queue.html#method.declared_message_count tells you the number of messages that were enqueued when the `Queue` instance was declared.
2. Performing a [`get`](https://docs.rs/amiquip/0.4.0/amiquip/struct.Queue.html#method.get) returns the current number of messages as part of its response (https://docs.rs/amiquip/0.4.0/amiquip/struct.Get.html#structfield.message_count), but only if there was at least one message in the queue.

Per the AMQP reference (https://www.rabbitmq.com/amqp-0-9-1-reference.html), I don't think there are any others ways to get this information.

**Comment by jgallagher** [comment]
I think that's not a super normal thing - asking the current number of enqueued messages is inherently racy since the number can easily change between the time when the server sent the number and when the client received it. That said, you definitely don't need to establish a new connection, and I don't know off the top of my head whether you need to create a new channel. You'd have to try it,  but you might be able to re-declare the same queue on the same channel multiple times just to get the current message count.

Glad the library is useful to you. :)
